"""
Paper Grade Transition Copilot
Historical Evidence Service
"""

from pathlib import Path
import json
import pandas as pd


PROJECT_ROOT = Path(__file__).resolve().parents[1]

RESULTS_DIR = PROJECT_ROOT / "reports" / "model_results"

EVIDENCE_JSON = RESULTS_DIR / "stabilization_evidence.json"
EVIDENCE_CSV = RESULTS_DIR / "stabilization_evidence.csv"


def load_evidence_json():
    """
    Load historical stabilization evidence generated by Stage 6.
    """

    if not EVIDENCE_JSON.exists():
        raise FileNotFoundError(
            f"Evidence JSON not found:\n{EVIDENCE_JSON}"
        )

    with open(EVIDENCE_JSON, "r", encoding="utf-8") as file:
        return json.load(file)


def load_evidence_csv():
    """
    Load historical evidence CSV.
    """

    if not EVIDENCE_CSV.exists():
        raise FileNotFoundError(
            f"Evidence CSV not found:\n{EVIDENCE_CSV}"
        )

    return pd.read_csv(EVIDENCE_CSV)


def get_transition_evidence(grade_from, grade_to):
    """
    Find historical evidence for a particular grade transition.
    """

    evidence = load_evidence_csv()

    required_columns = {
        "grade_from",
        "grade_to"
    }

    if not required_columns.issubset(evidence.columns):
        return {
            "message": "Historical transition evidence columns unavailable."
        }

    matching = evidence[
        (evidence["grade_from"].astype(str) == str(grade_from))
        &
        (evidence["grade_to"].astype(str) == str(grade_to))
    ]

    if matching.empty:
        return {
            "message": "No matching historical transition evidence found."
        }

    return {
        "records": matching.to_dict(orient="records")
    }


def get_stage6_summary():
    """
    Return the complete Stage 6 JSON summary.
    """

    return load_evidence_json()